version: '3.1'

services:

  db:
    image: postgres:15.4-alpine3.18
    container_name: jwt-postgres
    restart: always
    env_file:
      - .env 
    ports:
      - 5441:5432
    networks:
      - jwtnet

  api:
    container_name: jwt-authentication
    build: .
    ports:
      - 8080:3000
    restart: on-failure
    depends_on:
      - db
    networks:
      - jwtnet


networks:
  jwtnet:
    name: jwtnet
    driver: bridge